cabal-version:        3.0
name:                 FormulaManipulator
version:              0.1.0.0
author:               Lars van den Haak & Huub de Beer
maintainer:           l.b.v.d.haak@tue.nl
extra-source-files:   README.md

executable formulator
    main-is:          Main.hs
    build-depends:    base >=4.17.0.0 && < 4.20.0.0,
                      FormulaManipulator,
    hs-source-dirs:   app
    default-language: Haskell2010

library
    exposed-modules:  FormulaManipulator,
                      ExprLanguage,
    build-depends:    base >=4.17.0.0 && < 4.20.0.0,
                      parsec,
                      split,
                      containers
    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall

test-suite FormulatManipulator-test
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    build-depends:    
                      base >=4.17.0.0 && < 4.20.0.0,
                      hspec,
                      QuickCheck,
                      FormulaManipulator,
    ghc-options:      -Wall
